apiVersion: batch/v1
kind: CronJob
metadata:
  name: multiple-containers
spec:
  # run by cronjob-runner
  suspend: true
  schedule: '@annually'
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          initContainers:
            - name: init
              image: debian:stable
              command:
                - echo
                - '__INIT__'
          containers:
            - name: foo
              image: debian:stable
              command:
                - bash
                - -c
                - |
                  sleep 2
                  echo '__FOO__'
            - name: bar
              image: debian:stable
              command:
                - echo
                - '__BAR__'
