apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple
spec:
  # run by cronjob-runner
  suspend: true
  schedule: '@annually'
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: example
              image: debian:stable
              command:
                - bash
                - -c
                - |
                  set -eux
                  echo "Hello, world!"
                  date
                  uname -a
                  echo "FOO=$FOO"
                  exit 0
